---
title: "Awareness of USAID explore"
author: "dkillian"
date: "2020-12-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

#####

```{r global_options, include=F, warning=F, message=F, echo=F, error=F}

# standard figure size and generate clean output
knitr::opts_chunk$set(fig.width=10, fig.height=8, warning=FALSE, message=FALSE, cache=TRUE, error=T, echo=F)

```

```{r, include=F, warning=F, message=F, echo=F, error=F}
#source("code/00 BPPS - workflowr prep.R")

packages <- c("arm", "BMA", "brms", "corrplot", "dummies","DescTools", "estimatr","extrafont", "extrafontdb", "janitor", "reshape2","tidyr","broom", "haven", "HH","Hmisc","lubridate","knitr", "margins", "magrittr", "plotrix", "scales","survey", "srvyr", "sysfonts", "foreign","car", "ICC", "PowerUpR", "openxlsx", "ggrepel", "readr", "readxl", "sjmisc", "sjPlot", "sjstats", "sjlabelled", "skimr","labelled", "texreg", "janitor","psych","dplyr", "tidyverse", "bbplot", "viridis", "here", "ggridges", "ggthemes", "DT", "jtools", "huxtable", "stringi", "gghighlight", "plm", "rethinking" , "brms", "rstan", "rstanarm","tidybayes","texreg","gt","gtsummary","huxtable","stargazer", "gsynth", "panelView", "assertr", "pointblank", "validate", "sandwich", "knitr", "kableExtra", "formattable")

lapply(packages, library, character.only=T)

font_add_google("Source Sans Pro", "sans-serif")

options(digits=4, scipen=6)

# set default
theme_set(theme_bw() + theme(panel.grid.minor.x=element_blank(),
                             panel.grid.minor.y=element_blank(),
                             plot.title=element_text(face="bold",size=18, hjust=.5, family = "Source Sans Pro"),
                             plot.subtitle = element_text(size=16, family="Source Sans Pro"),
                             plot.caption=element_text(size=12, family="Source Sans Pro"),
                             axis.title=element_text(size=16, family="Source Sans Pro"),
                             axis.text=element_text(size=14, family="Source Sans Pro"),    
                             legend.text=element_text(size=14, family="Source Sans Pro"),
                             strip.text=element_text(size=14, family="Source Sans Pro"))) 


# without border
base_style <- function(){theme_bw() +
    theme(panel.grid.minor.x=element_blank(),
          panel.grid.minor.y=element_blank(),
          plot.title=element_text(face="bold",size=18, hjust=.5, family = "Source Sans Pro"),
          plot.subtitle = element_text(size=16, family="Source Sans Pro"),
          plot.caption=element_text(size=12, family="Source Sans Pro"),
          axis.title=element_text(size=16, family="Source Sans Pro"),
          axis.text=element_text(size=14, family="Source Sans Pro"),    
          legend.text=element_text(size=14, family="Source Sans Pro"),
          strip.text=element_text(size=14, family="Source Sans Pro"),
          panel.border=element_blank(),
          axis.ticks = element_blank()) 
}

# path <- "../BPPS analysis/data/BPPS hh instrument pre-codebook.xlsx"
path <- "data/BPPS hh instrument pre-codebook.xlsx"


labs <- path %>%
  excel_sheets() %>%
  set_names() %>%
  lapply(function(x) read_xlsx(x, path=path))

lablist <- names(labs) %>%
  as.data.frame()

yes <- labs$yes_no
agree4 <- labs$agree4
strat <- labs$strata

# dat <- read_rds("../BPPS analysis/data/prepared/BPPS prepared.rds")
dat <- read_rds("data/prepared/BPPS prepared.rds")

svydat <- svydesign(data = dat,
                    ids= ~PSU + A9,
                    strata = ~strata,
                    weights = ~Wgt1)


svyrdat <- dat %>%
  as_survey_design(ids= c(PSU,A9),
                   strata=strata,
                   weights=Wgt1)
```

#### B1. Are you aware of the United States Agency for International Development (USAID)?

```{r}

b1 <- svyrdat %>%
  group_by(B1) %>%
  summarise(proportion = survey_mean(),
            total = survey_total()) %>%
  as.data.frame() %>%
  left_join(yes,
            by=c("B1" = "yes_no_code")) %>%
  mutate(Percent=proportion,
         `Margin of error` = 1.96*proportion_se,
         Sample=round(total,0)) %>%
  select(Response, 
         Percent,
         `Margin of error`,
         Sample) %>%
  gt() %>%
  fmt_percent(vars(Percent, `Margin of error`),
              decimals=1)

b1

```

```{r}

b1_strat <- svyby(~aware,
                  ~strata,
                  FUN=svymean,
                  na.rm=T,
                  design=svydat)
```



